from Crypto.Cipher import AES

pt = bytearray.fromhex('255044462d312e350a25d0d4c5d80a34')
ct = bytearray.fromhex('d06bf9d0dab8e8ef880660d2af65aa82')
iv = bytearray.fromhex('09080706050403020100A2B2C2D2E2F2')

with open('keys.txt') as f:
    keys = f.readlines()

for k in keys:
    k = k.strip('\n')  # remove new line character generated by output
    key = bytearray.fromhex(k)
    cipher = AES.new(key, AES.MODE_CBC, iv=iv)
    new_ct = cipher.encrypt(pt)
    if new_ct == ct:
        print(f'Found secret key: {k}')
        exit(0)

print('No key found')
exit(1)


